global:
  evaluation_interval: 10s
  scrape_interval: 10s
  scrape_timeout: 5s
scrape_configs:
- job_name: yolov8-module
  static_configs:
  - labels:
      model: yolov8
      module: yolov8
    targets:
    - yolov8-module:8080
- job_name: peoplenet-module
  static_configs:
  - labels:
      model: peoplenet
      module: peoplenet
    targets:
    - peoplenet-module:8080
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
